### ISSUE TITLE
Add cache cleaning command

### ISSUE THREAD

**Issue by shimberger** [shimberger/gohls#10]
Add a subcommand to clean all caches.

**Comment by genofire** [comment]
please revert it -> cache cleaning as command is misleading (it do not make any validation if movie is watching).

This same job make `rm -R ~/.gohls/*` 
And `find ~/.gohls -type f -mmin +360 -delete` (delete only files created 6h ago) make it much better job.

Creating a cronjob is still nessasary.

---

(Maybe you want to create a "cronjob" inside of `server` that would be nice :smile: )
