### ISSUE TITLE
Binary release 0.1.0-win64 is a macOS binary

### ISSUE THREAD

**Issue by mappu** [shimberger/gohls#12]
```
$ md5sum gohls-windows-amd64-0.1.0.tar.gz
1f5d0a65cd4285beb22d856e292bb1c3 *gohls-windows-amd64-0.1.0.tar.gz

$ ./gohls.exe
bash: ./gohls.exe: cannot execute binary file: Exec format error

$ file gohls.exe
gohls.exe: Mach-O 64-bit x86_64 executable
```

Expected PE format.

Can you check the build script?

**Comment by shimberger** [comment]
Hey mappu. Thanks for the info! I am traveling today so will check back later. Thanks for the bugreport :)

**Comment by shimberger** [comment]
@mappu thanks again for catching that. I should have tested but didn't. The build script and binaries are fixed now.
