### ISSUE TITLE
release for linux i386?

### ISSUE THREAD

**Issue by esrrhs** [shimberger/gohls#20]

**Comment by avenwu** [comment]
@esrrhs You can compile from the source code. Just follow the `Developing it` section
I recently hands on this project in linux docker image  under OSX

**Comment by shimberger** [comment]
@esrrhs Sorry for not doing this earlier. I didn't get the notifications somehow. I added a build in a new release: https://github.com/shimberger/gohls/releases/tag/0.3.1
