### ISSUE TITLE
Error encoding on Ubuntu 16.04 using Linux snapshot

### ISSUE THREAD

**Issue by stanleyye** [shimberger/gohls#30]
Using the linux snapshot on ubuntu 16.04.
Downloading the video from the UI works completely fine but I can't play the video
```
Path to ffmpeg executable: /usr/local/bin/ffmpeg
Path to ffprobe executable: /usr/local/bin/ffprobe
HLS data directory: /home/stan/.gohls/
Visit http://localhost:8080/
ERRO[002] Error encoding Command failed exit status 1
```

**Comment by shimberger** [comment]
Thanks for the report 👍 

Could you re-run the program with the environment `DEBUG` set to 1 and look at the output?

So like this ``DEBUG=1 gohls serve -c <config-file>``?

**Comment by stanleyye** [comment]
Path to ffmpeg executable: /usr/local/bin/ffmpeg
Path to ffprobe executable: /usr/local/bin/ffprobe 
HLS data directory: /home/stan/.gohls/
Visit http://localhost:8080/
DEBU[0006] HTTP GET /                                   
DEBU[0006] SPA HTTP handling fallback                   
DEBU[0006] HTTP GET /static/js/main.c5bf51d7.js         
DEBU[0006] HTTP GET /static/css/main.adb407c9.css       
DEBU[0006] HTTP GET /api/list/                          
DEBU[0006] HTTP GET /static/media/roboto-latin-400.5d4aeb4e.woff2 
DEBU[0006] HTTP GET /static/media/roboto-latin-500.28546717.woff2 
DEBU[0006] HTTP GET /favicon.ico                        
DEBU[0008] HTTP GET /api/list/98ab19792c2732709516731b81e04f135cccc99c/ 
DEBU[0008] Executing ffprobe for /home/stan/Downloads/mov (1).mp4 
DEBU[0008] ffprobe for /home/stan/Downloads/mov (1).mp4 returned%!(EXTRA map[string]interface {}=map[format:map[filename:/home/stan/Downloads/mov (1).mp4 nb_programs:0 duration:15.557367 probe_score:100 bit_rate:1858342 tags:map[major_brand:mp42 minor_version:0 compatible_brands:isommp42 creation_time:2016-10-26T15:20:08.000000Z] nb_streams:2 format_name:mov,mp4,m4a,3gp,3g2,mj2 format_long_name:QuickTime / MOV start_time:0.000000 size:3613864]]) 
DEBU[0008] Executing ffprobe for /home/stan/Downloads/mov.mp4 
DEBU[0008] ffprobe for /home/stan/Downloads/mov.mp4 returned%!(EXTRA map[string]interface {}=map[format:map[format_name:mov,mp4,m4a,3gp,3g2,mj2 format_long_name:QuickTime / MOV duration:15.557367 size:3613864 tags:map[major_brand:mp42 minor_version:0 compatible_brands:isommp42 creation_time:2016-10-26T15:20:08.000000Z] filename:/home/stan/Downloads/mov.mp4 nb_programs:0 bit_rate:1858342 probe_score:100 nb_streams:2 start_time:0.000000]]) 
DEBU[0008] HTTP GET /api/frame/98ab19792c2732709516731b81e04f135cccc99c/mov.mp4 
DEBU[0008] HTTP GET /api/frame/98ab19792c2732709516731b81e04f135cccc99c/mov (1).mp4 
DEBU[0017] HTTP GET /api/playlist/98ab19792c2732709516731b81e04f135cccc99c/mov.mp4 
DEBU[0017] Playlist request: mov.mp4                    
DEBU[0017] HTTP GET /api/segments/98ab19792c2732709516731b81e04f135cccc99c/mov.mp4/0.ts 
DEBU[0017] Stream request: mov.mp4/0.ts                 
DEBU[0017] Encoding requested /home/stan/Downloads/mov.mp4:0 
DEBU[0017] Encoding /home/stan/Downloads/mov.mp4:0      
DEBU[0017] Executing: /usr/local/bin/ffmpeg [-timelimit 45 -ss 0.00 -i /home/stan/Downloads/mov.mp4 -t 5.00 -vf scale=-2:720 -vcodec libx264 -preset veryfast -acodec aac -pix_fmt yuv420p -force_key_frames expr:gte(t,n_forced*5.000) -f ssegment -segment_time 5.00 -initial_offset 0.00 pipe:out%03d.ts] 
DEBU[0018] Encoding /home/stan/Downloads/mov.mp4:1      
ERRO[0018] Error encoding Command failed exit status 1  
DEBU[0018] Executing: /usr/local/bin/ffmpeg [-timelimit 45 -ss 5.00 -i /home/stan/Downloads/mov.mp4 -t 5.00 -vf scale=-2:720 -vcodec libx264 -preset veryfast -acodec aac -pix_fmt yuv420p -force_key_frames expr:gte(t,n_forced*5.000) -f ssegment -segment_time 5.00 -initial_offset 5.00 pipe:out%03d.ts] 
DEBU[0020] HTTP GET /api/segments/98ab19792c2732709516731b81e04f135cccc99c/mov.mp4/0.ts 
DEBU[0020] Stream request: mov.mp4/0.ts                 
DEBU[0020] Encoding requested /home/stan/Downloads/mov.m`p4:0 
ERRO[0080] Timeout encoding                             
DEBU[0083] HTTP GET /api/segments/98ab19792c2732709516731b81e04f135cccc99c/mov.mp4/0.ts 
DEBU[0083] Stream request: mov.mp4/0.ts                 
DEBU[0083] Encoding requested /home/stan/Downloads/mov.mp4:0 
DEBU[0093] HTTP GET /api/segments/98ab19792c2732709516731b81e04f135cccc99c/mov.mp4/0.ts 
DEBU[0093] Stream request: mov.mp4/0.ts                 
DEBU[0093] Encoding requested /home/stan/Downloads/mov.mp4:0

**Comment by shimberger** [comment]
@stanleyye Which ffmpeg Version are you using? Maybe there are some command line flags that do not work.

**Comment by stanleyye** [comment]
@shimberger 
```
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: 
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

```

**Comment by zzdts** [comment]
I get the same issue, ffmpeg is the newest version :

ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration:
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by elico** [comment]
@zzdts The current ubuntu 16.04 ffmpeg default version(fmpeg version 2.8.15-0ubuntu0.16.04.1 ) do not work with many files I have tested but the static ffmpeg build works just fine.
- https://johnvansickle.com/ffmpeg/

```
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder
```

**Comment by shimberger** [comment]
@elico Thanks for chiming in. I'll close this for now. @zzdts feel free to re-open if issue persists.
