### ISSUE TITLE
Unable to play MKV

### ISSUE THREAD

**Issue by Techassi** [shimberger/gohls#33]
I am unable to play MKV files. 
I serve the server like this and there is no unexpected output or error in the command line.

```
.\gohls serve -config config.json
Path to ffmpeg executable: C:\ffmpeg\bin\ffmpeg.exe
Path to ffprobe executable: C:\ffmpeg\bin\ffprobe.exe
HLS data directory: C:\Users\Techassi/.gohls/
Visit http://localhost:8080/
```

The only error I get is:

`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.`

and 

`Uncaught (in promise) DOMException: Failed to load because no supported source was found.`

**Comment by shimberger** [comment]
I just tried https://github.com/Matroska-Org/matroska-test-files/blob/master/test_files/test2.mkv?raw=true and it works for me. Which browser are you using? Have you tried a different one?

**Comment by shimberger** [comment]
@Techassi I am closing this because I suspect it's an issue with ffmpeg + specific MKV.

**Comment by elico** [comment]
@Techassi If you can upload a sample file it can be tested by other.
