### ISSUE TITLE
Do not expose at every port

### ISSUE THREAD

**Issue by genofire** [shimberger/gohls#34]
If you want only a internal port (and maybe run a tls proxy in front of it):

https://github.com/shimberger/gohls/blob/6005f1bf5b40cf35fe5988fc9d5da2282b925e09/cmd_serve.go#L71

pls use a `addr` parameter for it

**Comment by shimberger** [comment]
@genofire I changed the server to bind to 127.0.0.1 by default. You can use the `--listen` flag to specify address and port.

**Comment by genofire** [comment]
Works
