### ISSUE TITLE
[BUG] wrong schema

### ISSUE THREAD

**Issue by genofire** [shimberger/gohls#36]
gohls could not be used behind a HTTPS/TLS proxy, because it force the wrong schema here:

https://github.com/shimberger/gohls/blob/f6bf3dd369f840ba29b8fb5a7192acf06c66a321/hls/http_playlists.go#L46

**Comment by shimberger** [comment]
@genofire I added a patch to check the `X-Forwarded-Proto` header. Does that solve the issue?

**Comment by genofire** [comment]
Works nice for me :)

**Comment by genofire** [comment]
Thank you for all your work.
