### ISSUE TITLE
Videos are not streaming when I deploy the application in Amazon Cloud

### ISSUE THREAD

**Issue by MaruthiVSM** [shimberger/gohls#40]
I am seeing the below error when I access the application deployed in AWS Cloud:

ERRO[0153] Error handling request: Command failed exit status 1
2019/05/01 09:58:28 "GET http://xx.xx.xx.xx:8084/api/segments/720/0/5d8ddd858ba06700cf12fc90dca22043a837dc21/9f46ff0ffae869b3e009cc806209e2b6cd33e139 HTTP/1.1" from 106.51.20.48:24112 - 000 0B in 78.281254ms

**Comment by shimberger** [comment]
@MaruthiVSM I will get back to you but I am out of town until Sunday night. Do you have ffmpeg installed and is it in your ```PATH```?

**Comment by shimberger** [comment]
@MaruthiVSM Is this still an issue?

**Comment by shimberger** [comment]
@MaruthiVSM I'm closing this issue for cleaning up isssues. Please re-open if you want to talk again.
