### ISSUE TITLE
change url in frontend

### ISSUE THREAD

**Issue by ASVBPREAUBV** [shimberger/gohls#43]
Is it possible to change the url in the frontend to serve from proper domain?

**Comment by shimberger** [comment]
It usually uses the "Host" header. So it should just work.

If you use a proxy: The latest snapshot should support the "X-Forwarded-Host" header.

**Comment by ASVBPREAUBV** [comment]
will try. Thanks for the help

**Comment by shimberger** [comment]
I'm closing this. Please re-open if required.
