### ISSUE TITLE
Missing Linux AMD64 v 4 release tar.gz file

### ISSUE THREAD

**Issue by elico** [shimberger/gohls#46]
I wanted try this service for a Docker service which can act as a VOD directory but.. the V4 linux amd64 tar.gz is missing in the latest release.

**Comment by shimberger** [comment]
@elico You are right.. I forgot. I will change this with the next release. In the meantime you can use the current snapshot at: https://s3.amazonaws.com/gohls/gohls-linux-amd64-snapshot.tar.gz

**Comment by elico** [comment]
Thanks!
