### ISSUE TITLE
i dont have issues, with this setting in ffmpeg, might help gohls 

### ISSUE THREAD

**Issue by omgbox** [shimberger/gohls#48]
ffmpeg -i example.mp4  -c:v libx264 -crf 21 -preset veryfast  -c:a aac -b:a 128k -ac 2  -f hls -hls_time 4 -hls_playlist_type event /mnt/stream.m3u8

**Comment by shimberger** [comment]
@omgbox Thanks for your feedback. This does the encoding in one swoop and works fine. This project however tries to do the encoding on-demand to save on processing, so we would need a different command. I am still not giving up on the approach. I will close this issue but keep it around for reference. Thanks again :)
