### ISSUE TITLE
asset undefined when i run it on windows

### ISSUE THREAD

**Issue by shyandsy** [shimberger/gohls#49]
there is an error shows undefined Assets when i run it on windows

could you write a tutorial for how to build and run it ?

![image](https://user-images.githubusercontent.com/5271457/85975103-c6bd7b00-ba09-11ea-80e4-95a19f911bb2.png)

**Comment by shimberger** [comment]
Hey @shyandsy, thanks for the bug report. I will try it on Windows. I think it has something to do with the go-bindata not being maintaned anymore. I will look into it.

**Comment by shimberger** [comment]
@shyandsy I changed from go-bindata to go-rice for the asset code. Can you maybe try again?

**Comment by shimberger** [comment]
I'm closing this because of lack of feedback. Please re-open if needed.
