### ISSUE TITLE
use statik pack static file in to a go exxcutable

### ISSUE THREAD

**Issue by brownchow** [shimberger/gohls#72]
there is a Go package [statik](https://github.com/rakyll/statik) which can **embed files into a Go executable**, so  the release  pre_release.sh will be easier to write, and will be easy to deploy, since it only generate a go exxcutable file

**Comment by alai04** [comment]
Now gohls use go.rice to embed static files into executable file. It only generate one executable file.

**Comment by brownchow** [comment]
> Now gohls use go.rice to embed static files into executable file. It only generate one executable file.

Thanks a lot, I will read the source code carefully!
