### ISSUE TITLE
Add Linux (armV6l) Binary build.

### ISSUE THREAD

**Issue by X7md** [shimberger/gohls#79]
can add release to `armv6l`?
or if there a giude to build it by myself?

**Comment by X7md** [comment]
`pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.92+ #1514 Mon Jan 17 17:35:21 GMT 2022 armv6l GNU/Linux`

**Comment by X7md** [comment]
Any help to build it with Github Action of example?

**Comment by X7md** [comment]
I try build it locally with WSL on Windows and target Linux armV6l, and succeeded.

I will see if I can make it with Github Action.

**Comment by shimberger** [comment]
@X7md I am closing this issue but if you send me the golang architecture you need I can add it. @pzhlkj6612 added some builds to GitHub actions and you can also open a PR if you need more. I did add arm64 for linux however.
