### ISSUE TITLE
HLS VOD support?

### ISSUE THREAD

**Issue by KudryavtsevDmitry** [shimberger/gohls#80]
Hello. I have several questions about features

Does it support HLS VOD? If so, does it make it on-the-fly packaging (without writing/storing chunks on disk)
Does it support mp4, mp3 containers?

**Comment by shimberger** [comment]
@KudryavtsevDmitry Thanks for the questions:

I created this project to stream my video collection. It does encode on the fly but segments are cached on disk. It uses ffmpeg so mp4 should be no issue. Since it's for video I don't think mp3 will work. Unless I am misunderstanding...
